version: "3.8"

services:
  fastify-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastify-api:latest
    container_name: fastify-api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:3E6C1-16aE-3Bbab-FacDBa-b*fG2bBB@monorail.proxy.rlwy.net:28807/railway
      - PORT=8080
      - CALLBACK_URI=https://gwalk.cpe.eng.cmu.ac.th/api/login/google/callback
      - CALLBACK_URI_FACEBOOK=https://gwalk.cpe.eng.cmu.ac.th/api/login/facebook/callback
      - SECRET_KEY=fiaopfjiapfjiodamijioiofanninfdafsgwtrsgyrwtgrmioqtjip9erwtirwijijij
      - FRONTEND_URL=https://gwalk.cpe.eng.cmu.ac.th
      - MINIO_ENDPOINT=obs.cpe.eng.cmu.ac.th
      - MINIO_URL=https://obs.cpe.eng.cmu.ac.th
      - MINIO_ACCESSKEY=GyDcHQ2zr9NmI3tHqQ6M
      - MINIO_SECRETKEY=uhAbLe9O26RPkyc08FmdF6QKP26H8ibD40JsTprG
      - MINIO_PORT=443
      - MINIO_USESSL=true
      - CALLBACK_URI_GUEST=https://gwalk.cpe.eng.cmu.ac.th/api/guests/login/google/callback
    restart: always


  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_DB=gallery-walk
      - POSTGRES_USER=panthon
      - POSTGRES_PASSWORD=panthon160900
    ports:
      - "5432:5432"#     volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

#   minio:
#     image: minio/minio:latest
#     ports:
#       - "7000:9000"
#       - "7001:9001"
#     environment:
#       MINIO_ROOT_USER: minioadmin
#       MINIO_ROOT_PASSWORD: miniopassword
#     volumes:
#       - ./volume:/data
#     command: server --address ":9001" --console-address ":9000" /data
#     restart: always

# networks:
#   default:
#     driver: bridge

# volumes:
#   postgres_data:
